#!/bin/bash
#
# UniFi Protect Docker Init
# Copyright (C) 2020 Vinnie Simonetti
# Copyright (C) 2019 James T. Lee
#
# Starts the unifi-protect service and its database
#

echo "==Starting=="

# Start DB
pg_ctlcluster 10 main start

# Create modified pre-start script
echo "==Preparing UniFi Protect pre-start script=="
python3 /script_setup.py || true

# Run unifi's pre-start (mod).
# Note: as of 1.13.3, the pre-start is able to properly make the postgres user, but can't run the psql commands properly. Not sure if docker or UniFi-Protect
echo "==Running UniFi Protect pre-start script=="
source /etc/default/unifi-protect
source /usr/share/unifi-protect/app/hooks/docker_pre_start

# Run unifi
echo "==UniFi Protect is starting...=="
trap 'pkill node' SIGTERM
unifi-protect
echo "==UniFi Protect is shutting down...=="

# Stop DB
pg_ctlcluster 10 main stop

echo "==ShutDown=="
